spring.application.name=edge-relative
server.address=127.0.0.1
management.endpoints.web.exposure.include=health
management.endpoints.web.discovery.enabled=false
management.endpoint.health.show-details=never
